#
# 测试：docker-compose up
#
version: "3.4"

# (https://docs.docker.com/compose/compose-file/#extension-fields)
x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: '12m'
    max-file: '5'

x-deploy:
  &default-deploy
  restart_policy:
    condition: any
    delay: 5s

x-volumes:
  &es-home-dir
  /opt/elasticsearch/elasticsearch-6.4.0:/home/elasticsearch

x-volumes:
  &kibana-volumes
  - /opt/kibana/kibana-6.4.1-linux-x86_64:/home/kibana
  - ./kibana/conf/kibana.yml:/home/kibana/config/kibana.yml

x-volumes:
  &logstash-volumes
  - /opt/logstash/logstash-6.4.1:/home/logstash
  - ./logstash/conf/simple.conf:/home/logstash/config/simple.conf

x-command:
  &es-run
  /home/elasticsearch/bin/elasticsearch

x-command:
  &kibana-run
  /home/kibana/bin/kibana

x-command:
  &logstash-run
  /home/logstash/bin/logstash -f /home/logstash/config/simple.conf

services:
#  elasticsearch_master1:
#    image: elasticsearch:latest
#    ports:
#      - 9210:9210
#      - 9310:9310
#    command: *es-run
#    volumes:
#      - *es-home-dir
#      - ./elasticsearch/conf/elasticsearch_master1.yml:/home/elasticsearch/config/elasticsearch.yml
#      - /opt/elasticsearch/data/master1:/home/elasticsearch/data
#    deploy: *default-deploy
#    logging: *default-logging
#
#  elasticsearch_master2:
#    image: elasticsearch:latest
#    ports:
#      - 9211:9211
#      - 9311:9311
#    command: *es-run
#    volumes:
#      - *es-home-dir
#      - ./elasticsearch/conf/elasticsearch_master2.yml:/home/elasticsearch/config/elasticsearch.yml
#      - /opt/elasticsearch/data/master2:/home/elasticsearch/data
#    deploy: *default-deploy
#    logging: *default-logging
#
#  elasticsearch_data1:
#    image: elasticsearch:latest
#    ports:
#      - 9200:9200
#      - 9300:9300
#    command: *es-run
#    volumes:
#      - *es-home-dir
#      - ./elasticsearch/conf/elasticsearch_data1.yml:/home/elasticsearch/config/elasticsearch.yml
#      - /opt/elasticsearch/data/data1:/home/elasticsearch/data
#    deploy: *default-deploy
#    logging: *default-logging
#
#  elasticsearch_data2:
#    image: elasticsearch:latest
#    ports:
#      - 9201:9201
#      - 9301:9301
#    command: *es-run
#    volumes:
#      - *es-home-dir
#      - ./elasticsearch/conf/elasticsearch_data2.yml:/home/elasticsearch/config/elasticsearch.yml
#      - /opt/elasticsearch/data/data2:/home/elasticsearch/data
#    deploy: *default-deploy
#    logging: *default-logging
#
#  kibana:
#    image: kibana:latest
#    ports:
#      - 5601:5601
#    command: *kibana-run
#    volumes: *kibana-volumes
#    deploy: *default-deploy
#    logging: *default-logging
#    depends_on:
#      - elasticsearch_master1
#      - elasticsearch_master2
#      - elasticsearch_data1
#      - elasticsearch_data2

  logstash:
    image: logstash:latest
    ports:
      - 9600:9600
    command: *logstash-run
    volumes: *logstash-volumes
    deploy: *default-deploy
    logging: *default-logging
#    depends_on:
#      - elasticsearch_master1
#      - elasticsearch_master2
#      - elasticsearch_data1
#      - elasticsearch_data2