#
# 测试：docker-compose up
#
version: "3.2"
services:
  elasticsearch_master1:
    image: elasticsearch:latest
    ports:
      - 9210:9210
      - 9310:9310
    command: /home/elasticsearch/bin/elasticsearch
    volumes:
      - /opt/elasticsearch/elasticsearch-6.4.0:/home/elasticsearch
      - ./elasticsearch/conf/elasticsearch_master1.yml:/home/elasticsearch/config/elasticsearch.yml
      - /opt/elasticsearch/data/master1:/home/elasticsearch/data
  elasticsearch_master2:
    image: elasticsearch:latest
    ports:
      - 9211:9211
      - 9311:9311
    command: /home/elasticsearch/bin/elasticsearch
    volumes:
      - /opt/elasticsearch/elasticsearch-6.4.0:/home/elasticsearch
      - ./elasticsearch/conf/elasticsearch_master2.yml:/home/elasticsearch/config/elasticsearch.yml
      - /opt/elasticsearch/data/master2:/home/elasticsearch/data
  elasticsearch_data1:
    image: elasticsearch:latest
    ports:
      - 9200:9200
      - 9300:9300
    command: /home/elasticsearch/bin/elasticsearch
    volumes:
      - /opt/elasticsearch/elasticsearch-6.4.0:/home/elasticsearch
      - ./elasticsearch/conf/elasticsearch_data1.yml:/home/elasticsearch/config/elasticsearch.yml
      - /opt/elasticsearch/data/data1:/home/elasticsearch/data
  elasticsearch_data2:
    image: elasticsearch:latest
    ports:
      - 9201:9201
      - 9301:9301
    command: /home/elasticsearch/bin/elasticsearch
    volumes:
      - /opt/elasticsearch/elasticsearch-6.4.0:/home/elasticsearch
      - ./elasticsearch/conf/elasticsearch_data2.yml:/home/elasticsearch/config/elasticsearch.yml
      - /opt/elasticsearch/data/data2:/home/elasticsearch/data
  kibana:
    image: kibana:latest
    ports:
      - 5601:5601
    command: /home/kibana/bin/kibana
    volumes:
      - /opt/kibana/kibana-6.4.1-linux-x86_64:/home/kibana
      - ./kibana/conf/kibana.yml:/home/kibana/config/kibana.yml
    depends_on:
      - elasticsearch_master1
      - elasticsearch_master2
      - elasticsearch_data1
      - elasticsearch_data2