version: "3.4"

x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: '12m'
    max-file: '5'

services:
  es_single:
    image: elasticsearch:6.4.3
    container_name: es_single
    ports:
      - 9200:9200
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - node.master=true
      - node.data=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g -Des.insecure.allow.root=true"
    volumes:
      - /es/single_data:/usr/share/elasticsearch/data
    restart: always
    logging: *default-logging
    networks:
      - mynet1

  kibana:
    image: kibana:6.4.3
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es_single:9200
    depends_on:
      - es_single
    restart: always
    logging: *default-logging
    networks:
      - mynet1

networks:
  mynet1:
    driver: bridge
