#
# docker build -t spark-base -f Dockerfile-spark-base .
#
FROM logstash:6.4.3

ENV LOGSTASH_HOME=/usr/share/logstash

CMD ${LOGSTASH_HOME}/bin/logstash -f ${LOGSTASH_HOME}/config/default.conf --config.reload.automatic